Return-Path: <out-582911-B2C71BD37AF148CE9D728B61264F854D@mail.beliefnet.com>
X-Original-To: beliefnet@cp.monitor1.returnpath.net
Received: from mxa-d1.returnpath.net (unknown [10.8.2.117])
	by cpa-d1.returnpath.net (Postfix) with ESMTP id 447A219825C
	for <beliefnet@cp.monitor1.returnpath.net>; Fri,  1 Apr 2011 10:32:42 -0600 (MDT)

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.=
w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3Diso-8859-=
1">
<meta http-equiv=3D"Content-Type" content=3D"text/x-aol; charset=3Diso-8859=
-1">
<title>...</title>
</head>
<body bgcolor=3D"#ffffff">
<div align=3D"center" style=3D"font-size:8pt; font-family:arial,helvetica,s=
ans-serif; color:#666666;">
=09<table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"598">
=09=09=09<tr>
=09=09=09=09<td width=3D"139" bgcolor=3D"#dce8f7" align=3D"left"><img src=
=3D"http://bnimg1.beliefnet.com/ads/beliefnet/beliefnetlogo-1.gif" alt=3D"B=
eliefnet" width=3D"139" height=3D"31" border=3D"0"></td>
=09=09=09=09<td  width=3D"459" bgcolor=3D"#dce8f7" align=3D"center" valign=
=3D"bottom" style=3D"background-image:url(http://bnimg1.beliefnet.com/ads/b=
eliefnet/head-1.gif);background-repeat:repeat-x;"><font size=3D"2" color=3D=
"#012d54" style=3D"font-size:9px;line-height:12px;font-family:arial,helveti=
ca,sans-serif;">A&nbsp;&nbsp;&nbsp;&nbsp;S p o n s o r e d&nbsp;&nbsp;&nbsp=
;&nbsp;M e s s a g e&nbsp;&nbsp;&nbsp;&nbsp;f r o m&nbsp;&nbsp;&nbsp;&nbsp;=
B e l i e f n e t</font></td>
=09=09=09</tr>
=09=09=09<tr>
=09=09=09=09<td width=3D"139" bgcolor=3D"#e1efff" align=3D"left"><img src=
=3D"http://www.beliefnet.com/media/spacer.gif" alt=3D"" width=3D"139" heigh=
t=3D"21" border=3D"0"></td>
=09=09=09=09<td width=3D"459" bgcolor=3D"#e1efff" align=3D"center" valign=
=3D"top" style=3D"background-image:url(http://bnimg1.beliefnet.com/ads/beli=
efnet/head-2.gif);background-repeat:repeat-x;"><font color=3D"#012d54" styl=
e=3D"font-size:8pt; font-family:arial,helvetica,sans-serif;">Unsubscribe in=
structions are at the bottom of this email.</font><br><font size=3D"1" styl=
e=3D"font-size:9px;line-height:12px;">P A I D &nbsp;&nbsp; A D V E R T I S =
E M E N T</font>
=09=09=09=09</td>
=09=09=09</tr>
=09=09=09<tr>
=09=09=09=09<td width=3D"139" style=3D"background-image:url(http://bnimg1.b=
eliefnet.com/ads/beliefnet/shadow-1.gif);background-repeat:repeat-x;"><img =
src=3D"http://bnimg1.beliefnet.com/ads/beliefnet/shadow-1.gif" alt=3D"" wid=
th=3D"139" height=3D"7" border=3D"0"></td>
=09=09=09=09<td width=3D"459" style=3D"background-image:url(http://bnimg1.b=
eliefnet.com/ads/beliefnet/shadow-2.gif);background-repeat:repeat-x;"><img =
src=3D"http://bnimg1.beliefnet.com/ads/beliefnet/shadow-2.gif" alt=3D"" wid=
th=3D"459" height=3D"7" border=3D"0"></td>
=09=09=09</tr>
=09=09</table>

<br>
</div>
<div align=3D"center" style=3D"padding:10px;">
<table align=3D"center" width=3D"728" border=3D"0" cellpadding=3D"0" cellsp=
acing=3D"0">

=09<tr>

=09=09<td valign=3D"top">

=09<a   href=3D"http://click1.mail.beliefnet.com/xbskvqjdklhtjnmdtpsqytcljv=
tskbdvbpmsrpljjbgsj_rgckrjrcvgl.html" style=3D"text-decoration: none;" targ=
et=3D"_blank" >
=09=09=09<img src=3D"http://bnimg1.beliefnet.com/ads/chcknsp/110402c1_01.jp=
g" width=3D"428" height=3D"218" alt=3D"Chicken Soup for the Soul" border=3D=
"0"  style=3D"vertical-align:bottom" /> </a></td>

=09=09<td valign=3D"top">
<a   href=3D"http://click1.mail.beliefnet.com/bqzvlmcpvkfycstpyjbmnyzkclybv=
qplqjtbgjkccqdbb_rgckrjrcvgl.html" style=3D"text-decoration: none;" target=
=3D"_blank" >
=09=09=09<img src=3D"http://bnimg1.beliefnet.com/ads/chcknsp/110402c1_02.jp=
g" width=3D"300" height=3D"218" alt=3D"Changing the World One Story at a Ti=
me (TM)" border=3D"0"  style=3D"vertical-align:bottom" /></a></td>

=09</tr>

=09<tr>

=09=09<td width=3D"428" valign=3D"top">
<a   href=3D"http://click1.mail.beliefnet.com/jqscrkqbchjwqzdbwtfkpwnhqrwfc=
mbrmtdfvthqqmsfn_rgckrjrcvgl.html" style=3D"text-decoration: none;" target=
=3D"_blank" >
=09=09=09<img src=3D"http://bnimg1.beliefnet.com/ads/chcknsp/110402c1_03.jp=
g" width=3D"428" height=3D"109" border=3D"0" alt=3D"Improving your life one=
 story at a time" /></a>



=09=09=09<div style=3D"margin:0 12px 0 25px;width:378px;font-family:Arial,H=
elvetica,sans-serif;font-size:14px;color:#666;">

=09=09=09

=09=09=09=09=09
=09=09=09=09<p style=3D"font-size:19px;font-weight:bold;margin:.7em 0 1em 0=
;">Life View<br />

=09=09<span style=3D"font-size:17px;"><em>From Chicken Soup for the Soul: T=
hink Positive</em></span></p>

<p style=3D"margin:0 0 1em 0;"><strong>By Spring Stafford</strong></p>



=09=09=09=09<p style=3D"margin:0 0 1em 0;"><em>Never, never, never give up.=
<br />
  ~Winston Churchill</em></p>

=09

=09<div style=3D"text-indent:16px;font-size:14px;">






<p style=3D"margin-bottom:20px;">It was Easter vacation and I was home from=
 the university for ten glorious days. I knew how much my mother missed me =
while I was at school and I knew she was going to cook all of my favorite f=
oods and spoil me rotten.</p>
<p style=3D"margin-bottom:20px;">I was an art student and would graduate wi=
th my degree in two months and I had just been given a scholarship to atten=
d a university in England for two years. I'd never been happier.</p>
<p style=3D"margin-bottom:20px;">Friday night I stayed up late to watch a f=
unny movie on TV with my mother and older brother and we laughed until our =
sides ached. It was good to be home again.</p>
<p style=3D"margin-bottom:20px;">Saturday morning I woke up and couldn't se=
e out of my right eye.</p>
<p style=3D"margin-bottom:20px;">&quot;Mom, something is wrong with my eye!=
&quot; I said. I wasn't too scared because I thought it was a simple infect=
ion or allergic reaction to something.</p>
<p style=3D"margin-bottom:20px;">My mother took me to an eye doctor and he =
took one look at my eye and ordered us to catch a plane to get to a hospita=
l hundreds of miles away. He said he'd call ahead and make arrangements for=
 a specialist to examine me. He wouldn't tell us what was wrong. My mother =
said maybe a sliver of glass or something had gotten into my eye and they'd=
 have to remove the splinter and I'd be fine.</p>





=09</div>

=09=09=09

=09=09=09<p style=3D"margin-bottom:20px;"><a href=3D"http://click1.mail.bel=
iefnet.com/lhkskcwmspgrwfymrdqclrhpwkrqsnmkndyqjdpwwnzhz_rgckrjrcvgl.html" =
target=3D"_blank"><img src=3D"http://bnimg1.beliefnet.com/ads/chcknsp/11040=
2c1_04.jpg" width=3D"92" height=3D"28" border=3D"0" alt=3D"Read More" /></a=
></p>

=09=09=09

=09=09=09<p style=3D"margin:0 0 1em 0;"><a href=3D"http://click1.mail.belie=
fnet.com/ucwvqkphvbwspzdhsgmkjscbpqsmvfhqfgdmngbppfych_rgckrjrcvgl.html" ta=
rget=3D"_blank"><img src=3D"http://bnimg1.beliefnet.com/ads/chcknsp/faceboo=
k.gif" width=3D"84" height=3D"16" alt=3D"Facebook" border=3D"0" /></a></p>

=09=09=09

=09=09=09<p style=3D"margin:0 0 1em 0;"><a href=3D"http://click1.mail.belie=
fnet.com/oqksznrtsgjdrcvtdkmnpdqgrzdmsltzlkvmwkgrrlfqz_rgckrjrcvgl.html" ta=
rget=3D"_blank"><img src=3D"http://bnimg1.beliefnet.com/ads/chcknsp/twitter=
.gif" width=3D"72" height=3D"16" alt=3D"Twitter" border=3D"0" /></a></p>

=09=09

=09=09</div>

=09=09</td>

=09=09<td width=3D"300" align=3D"right" valign=3D"top">

=09=09

=09=09
<p style=3D"margin:0 0 1em 0;">
<!--/* OpenX Image Tag v2.8.6-rc2 */-->
<a href=3D'http://click1.mail.beliefnet.com/tpvszrmlsfhkmdglkbjrtkpfmzkjscl=
zcbgjvbfmmcwph_rgckrjrcvgl.html' target=3D'_blank'><img src=3D'http://d1.op=
enx.org/avw.php?zoneid=3D186727&amp;sourceid=3D-BN_110402-&amp;n=3Da1e53d33=
' width=3D"300" height=3D"250" alt=3D"Advertisement" border=3D"0" /></a>
</p>

=09<p style=3D"margin:0 0 1em 0;"><a href=3D"http://click1.mail.beliefnet.c=
om/vygdvzjfdbpnjqtfnkmzcnybjvnmdgfvgktmhkbjjgryk_rgckrjrcvgl.html" target=
=3D"_blank"><img src=3D"http://bnimg1.beliefnet.com/ads/chcknsp/110402c1_05=
.jpg" width=3D"300" height=3D"242" border=3D"0" alt=3D"Chicken Soup for the=
 Soul: Think Positive" /></a></p>


<p style=3D"margin:0 0 1em 0;">
<!--/* OpenX Image Tag v2.8.6-rc2 */-->
<a href=3D'http://click1.mail.beliefnet.com/fygtslgdtzhwgcfdwbrlpwyzgswrtnd=
snbfrjbzggnqyj_rgckrjrcvgl.html' target=3D'_blank'><img src=3D'http://d1.op=
enx.org/avw.php?zoneid=3D186738&amp;sourceid=3D-BN_110402-&amp;n=3Da2f6964c=
' width=3D"300" height=3D"250" alt=3D"Advertisement" border=3D"0" /></a>
</p>
=09=09=09=09

=09=09

=09=09</td>

=09</tr>

<tr>

=09=09<td colspan=3D"2" valign=3D"top">

=09=09=09<p style=3D"margin-top:20px;text-align:center;"><a href=3D"http://=
click1.mail.beliefnet.com/vymdvzjfdbpnjqtfnkmzcnybjvnmdgfvgktmhkbjjgryg_rgc=
krjrcvgl.html" target=3D"_blank"><img src=3D"http://bnimg1.beliefnet.com/ad=
s/chcknsp/110402c1_06.jpg" width=3D"728" height=3D"48" border=3D"0" alt=3D"=
Please visit our website at www.ChickenSoup.com" /></a></p>

=09=09=09<div style=3D"text-align:center;font-family:Arial,Helvetica,sans-s=
erif;font-size:13px;color:#666;">

=09=09=09<p style=3D"margin:1em 0 1em 0;">Chicken Soup for the Soul Publish=
ing, LLC, P.O. Box 700, Cos Cob, CT 06807<br />

=09=09=09To unsubscribe from this e-mail please <a href=3D"http://click1.ma=
il.beliefnet.com/bzzvlmcpvkfycstpyjbmnyzkclybvqplqjtbgjkccqdzc_rgckrjrcvgl.=
html" style=3D"color:#ab171a;" target=3D"_blank">click here</a>.</p>

=09=09=09</div>

=09=09</td>

=09</tr></table>

<img src=3D"http://click1.mail.beliefnet.com/ygbyltbsyrqnbpzsnfctwnvrblncyg=
slgfzckfrbbgmcg_rgckrjrcvgl.gif" width=3D"0" height=3D"0"> </body>

</html>
=09=09</div>
=09=09<table width=3D"565" border=3D"0" cellspacing=3D"0" cellpadding=3D"0"=
 align=3D"center">
=09=09=09<tr>
=09=09=09=09<td valign=3D"top" align=3D"left">
=09=09=09=09=09<hr width=3D"565" size=3D"1">
=09=09=09=09=09<table width=3D"565" border=3D"0" cellspacing=3D"0" cellpadd=
ing=3D"10" bgcolor=3D"#F5F9FC">
=09=09=09=09=09=09<tr>
=09=09=09=09=09=09=09<td valign=3D"top" align=3D"left">
=09=09=09=09=09=09=09=09<font face=3D"verdana,arial,sans-serif" size=3D"1" =
color=3D"#666666">
=09=09=09=09=09=09=09=09To view this email as a web page <a href=3D"http://=
click1.mail.beliefnet.com/ViewMessage.do?a=3Dview&m=3Dbdqfgpqp&r=3Drgckrjrc=
vgl&s=3Dozwsznrtsgjrcvtkmnpqgrzmsltzlkvmwkg">follow this link</a>.
=09=09=09=09=09=09=09=09<br><br>
=09=09=09=09=09=09=09=09This email was requested by: &#123;beliefnet@cp.mon=
itor1.returnpath.net&#125;<br><br>
=09=09=09=09=09=09=09=09<strong>Unsubscribe from advertisements, but keep y=
our newsletters:</strong> <a href=3D"http://www.beliefnet.com/newsletter/un=
subscriberequest.aspx?recipientid=3D42021659&externalid=3D31a21254104102c47=
31bc338dc3e7628&listid=3D33&tracking=3Dunsub" target=3D"_blank"><font color=
=3D"#0000FF">unsubscribe me</font></a><br><br>
=09=09=09=09=09=09=09=09<strong>Manage your Beliefnet subscriptions includi=
ng newsletters and advertisements:</strong> <a href=3D"http://www.beliefnet=
.com/Newsletter/Manage.aspx?tracking=3Dunsub" target=3D"_blank"><font color=
=3D"#0000FF">unsubscribe me</font></a><br><br>
=09=09=09=09=09=09=09=09<strong>Unsubscribe by mail:</strong> Beliefnet, P.=
O. Box 3882, Norfolk, VA 23514-3882<br><br>
=09=09=09=09=09=09=09=09<strong>Change your email address:</strong>
=09=09=09=09=09=09=09=09<a href=3D"http://www.beliefnet.com/user/nl_updemai=
l.asp" target=3D"_blank">
=09=09=09=09=09=09=09=09<font color=3D"#0000FF">http://www.beliefnet.com/us=
er/nl_updemail.asp</font></a><br><br>
=09=09=09=09=09=09=09=09<strong>Privacy statement:</strong>
=09=09=09=09=09=09=09=09<a href=3D"http://www.beliefnet.com/about/privacy.a=
sp"><font color=3D"#0000FF">http://www.beliefnet.com/about/privacy.asp</fon=
t></a> </font>
=09=09=09=09=09=09=09</td>
=09=09=09=09=09=09</tr>
=09=09=09=09=09</table>
=09=09=09=09</td>
=09=09=09</tr>
=09=09</table>
=09
=09</body>
</html>
